config/routes.rb
Rails.application.routes.draw do
  get 'slots/new'
  get 'rooms/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/openslot', to: 'slots#show'
  get '/adduser', to: 'srecords#new'
  get '/showSlotUsers', to: 'srecords#show'
  get '/addtoslot', to: 'srecords#new'
  post '/addtoslot', to: 'srecords#create'
  get '/response', to: 'urecords#yes'
  get '/responseno', to: 'urecords#no'
  get '/showroom', to: 'rooms#show'
   get  '/help',    to: 'static_pages#help'
   get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
get '/newroom', to: 'rooms#new'
post '/newroom', to: 'rooms#create'
  resources :users do
    resources :urecords
  end
    resources :rooms do
    resources :slots do
      resources :srecords
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
class Slot < ApplicationRecord
  has_many :srecord
  belongs_to :room
  before_save :generate_token
  validates :name, presence: true
  validates :start, presence: true
  validate :valid_start
  validates :stop, presence: true
  validate :valid_stop
  validates :description, presence: true

  def valid_start

    if start.present? && stop.present?
      if start.to_time.hour < 9
        errors.add(:start,"Not within Office Timings")
       end
      slot=room.slot.all
      slot.each do |s|
        if start.between?(s.start, s.stop-1) || stop.between?(s.start, s.stop-1)
          errors.add(:start,"Overlapping")
        end
      end
         end
      # queryslot= Slot.all
      # queryslot.each do |q|
      #   puts start
      #   puts "testbug"
      #   if start.between?(q.start, q.stop-1) || stop.between?(q.start, q.stop-1)
      #     errors.add(:start)
      #   end
      # end

  end
  def valid_stop
      if start.present? && stop.present?
  if stop.to_time.hour>20
    errors.add(:stop, "Not within Office Timings")
end
if(stop.to_time-start.to_time<=1800)
  errors.add(:stop, "Minimum duration is 30 mins")
  end
end

  def generate_token
   self.token = loop do
     token = SecureRandom.urlsafe_base64(nil, false)
     break token unless self.class.exists?(token: token)
   end
 end
end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
def form
end
def show
  @room=Room.find(params[:room_id])
  @slot=@room.slot.find(params[:slot_id])
end
def showUsers
  @room=Room.find(params[:room_id])
  @slot = @room.slot.find(params[:id])
end
def create

   @room = Room.find(params[:room_id])

   @slot = @room.slot.build(slot_params)
   if @slot.save
     redirect_to room_path(@room)
   else
     flash[:danger]=@slot.errors.full_messages.join('.')
      redirect_to room_path(@room)
   end
 end
  def destroy
   @room = Room.find(params[:room_id])
   @slot = @room.slot.find(params[:id])
   @slot.destroy
   redirect_to room_path(@room)
 end
 private
   def slot_params
     params.require(:slot).permit(:start, :stop, :name, :description)
   end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with(model: [ @room, @room.slot.build ], local: true) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name, class: 'form-control' %>
</p>
<p>
  <%= f.label :description %><br>
  <%= f.text_field :description, class: 'form-control' %>
</p>
  <p>
    <%= f.label :start %><br>
    <%= f.time_field :start, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :stop %>
    <%= f.time_field :stop, class: 'form-control' %>

  </p>

  <p>
          <%= f.submit "Create Slot", class: "btn btn-info btn-lg" %>
    </p>
<% end %>

app/views/slots/_slot.html.erb
<div class="col-sm-4 card">
<br>
<p>
  <strong>Name:</strong>
  <%= slot.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= slot.description %>
    </p>
<p>
  <strong>ID:</strong>
  <%= slot.id %>
  </p>
    <p>
  <strong>Start Time: </strong>
  <%= slot.start.to_formatted_s(:time) %>
  </p>

  <p>
    <strong>Stop Time: </strong>
    <%= slot.stop.to_formatted_s(:time) %>
    </p>


<br>
<div class="center">
  <%= link_to "Open", openslot_path(:room_id => @room.id, :slot_id => slot.id) , class:"btn btn-info btn-sm"%>
<%# link_to "Add Users", adduser_path(:room_id => @room.id, :slot_id => slot.id) , class:"btn btn-info btn-sm"%>
<div style="height:1vh"></div>
<%# link_to "Display users", showSlotUsers_path(:room_id => @room.id, :slot_id => slot.id) , class:"btn btn-warning btn-sm"%>
</div>
<br>
<br>
</div>

app/views/slots/new.html.erb
<% provide(:title, 'New Slot') %>
<h1>Create a new slot</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@slot, url: slotadd_path) do |f| %>
      <%= render 'shared/error_messages_slot' %>

      <%= f.label :start %>
      <%= f.time_field :start, class: 'form-control' %>

      <%= f.label :stop %>
      <%= f.time_field :stop, class: 'form-control' %>
      <%= f.label :people %>
      <%= f.number_field :people, class: 'form-control' %>

      <%= f.submit "Create Slot", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/slots/show.html.erb
<% provide(:title, Slot) %>
<div class="row">
  <aside>

    <section class="user_info">

      <h1><%=@slot.name%></h1>
      <h2><%=@slot.description%></h2>
    </section>
    <section>
      <div class="flexbox">
    <%= render User.all %>
    </div>
      </section>
      <section>
        </section>
  </aside>
</div>

app/views/slots/showUsers.html.erb
<% provide(:title, Slot) %>

  <aside>
    <section class="user_info">
      <h1>Room
      <%= @room.id %>
       </h1>
      <h1>Slot
        <%= @slot.id %>
      </h1>
    </section>

      <div class="flexbox">
    <%= render User.where(slot_id: @slot.id) %>
    </div>

  </aside>