config/routes.rb
Rails.application.routes.draw do
  get 'slots/new'
  get 'rooms/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/openslot', to: 'slots#show'
  get '/adduser', to: 'srecords#new'
  get '/showSlotUsers', to: 'srecords#show'
  get '/addtoslot', to: 'srecords#new'
  post '/addtoslot', to: 'srecords#create'
  get '/response', to: 'urecords#yes'
  get '/responseno', to: 'urecords#no'
  get '/showroom', to: 'rooms#show'
   get  '/help',    to: 'static_pages#help'
   get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
get '/newroom', to: 'rooms#new'
post '/newroom', to: 'rooms#create'
  resources :users do
    resources :urecords
  end
    resources :rooms do
    resources :slots do
      resources :srecords
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
has_many :urecord
  before_save { self.email = email.downcase }
  before_save :generate_token
  validates :name,  presence: true, length: { maximum: 50 }
  APPROVED_DOMAINS = ["commutatus.com", "sarthakjha.com"]

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, if: :domain_check, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
                      has_secure_password
                      validates :password, presence: true, length: { minimum: 6 }

                      # Returns the hash digest of the given string.
                        def User.digest(string)
                          cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                                        BCrypt::Engine.cost
                          BCrypt::Password.create(string, cost: cost)
                        end

                        def domain_check
                          unless APPROVED_DOMAINS.any? { |word| email.end_with?(word)}
                            errors.add(:email, "is not from a valid domain")
                          end
                        end

                        def generate_token
                         self.token = loop do
                           token = SecureRandom.urlsafe_base64(nil, false)
                           break token unless self.class.exists?(token: token)
                         end
                       end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    render 'new'
  end
  def addSlot
    user= User.find(params[:user_id])
user.update_column(:room_id, params[:room_id].to_i)
  user.update_column(:slot_id, params[:slot_id].to_i)
  end

  def added
    rand="testtbugg"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<div  class="col-md-3 card">
  <br>
  <%= gravatar_for user %>
<h3><%= user.name %></h3>
<h2><%= user.email %></h2>
<% puts added(@slot, user) %>
<%puts "function caldled"%>
<%if !added(@slot, user)%>
<%=link_to "Add User", addtoslot_path(:slot_id => params[:slot_id], :user_id => user.id), method: :post, class:"btn btn-success btn-md" %>
<%else%>
<%rec= @slot.srecord.where(user_id: user.id).first%>
<p>Status:</p>
<%=rec.status%>
 <%end%>
<br>
<br>
</div>

app/views/users/_userbackup.html.erb
<%= user.name %>
<%= user.email %>

<%= link_to "add user", test_path(:id => "test"), addtoslot_path(:slot_id => params[:slot_id], :user_id => user.id), method: :post, remo %>

<br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div style="margin-left:-25%">
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-info btn-lg" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
            <h3 class="center">Available Rooms</h3>
    <div class="row">
    <%= render  Room.all %>
</div>
<br>
<br>
<h3 class="center" style="margin-top:5%;">Current Meetings</h3>

  <div class="row">
    <%= render @user.urecord.order(:created_at) %>

</div>

        <br>

</div>