config/routes.rb
Rails.application.routes.draw do
  get 'slots/new'
  get 'rooms/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/openslot', to: 'slots#show'
  get '/adduser', to: 'srecords#new'
  get '/showSlotUsers', to: 'srecords#show'
  get '/addtoslot', to: 'srecords#new'
  post '/addtoslot', to: 'srecords#create'
  get '/response', to: 'urecords#yes'
  get '/responseno', to: 'urecords#no'
  get '/showroom', to: 'rooms#show'
   get  '/help',    to: 'static_pages#help'
   get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
get '/newroom', to: 'rooms#new'
post '/newroom', to: 'rooms#create'
  resources :users do
    resources :urecords
  end
    resources :rooms do
    resources :slots do
      resources :srecords
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/urecord.rb
class Urecord < ApplicationRecord
  belongs_to :user
end

app/controllers/urecords_controller.rb
class UrecordsController < ApplicationController
  def new
end

  def create
  end

def yes
urec=Urecord.find_by(slot_id: params[:slot_id])
srec=Srecord.find_by(user_id: params[:user_id])
srec.update_column(:status, "Confirmed")
urec.update_column(:status, "Accepted")
flash[:success] = "Accepted Invitation"
redirect_back(fallback_location: root_path)
end
def no
  urec=Urecord.find_by(slot_id: params[:slot_id])
  srec=Srecord.find_by(user_id: params[:user_id])
srec.update_column(:status, "Declined")
urec.update_column(:status, "Declined")
flash[:danger] = "Declined Invitation"
redirect_back(fallback_location: root_path)
end
end

app/helpers/urecords_helper.rb
module UrecordsHelper
end

app/views/urecords/_urecord.html.erb
<%slot=Slot.find(urecord.slot_id)%>

<div class="col-sm-2 center card">
<br>
<p>
  <strong>Slot ID:</strong>
  <%= slot.id %>
  </p>
    <p>
  <strong> Slot Start: </strong>
  <%= slot.start.to_formatted_s(:time) %>
  </p>

  <p>
    <strong> Slot Stop: </strong>
    <%= slot.stop.to_formatted_s(:time) %>
    </p>

    <p>
      <strong> People: </strong>
   <%= slot.people %>
      </p>
      <p>
        <strong> Current Status: </strong>
     <%= urecord.status %>
        </p>
      <p>
  <%= link_to "Accept", response_path(:slot_id => slot.id, :user_id => @user.id), class:"btn btn-sm btn-success"%>
  <div></div>
  <%= link_to "Decline", responseno_path(:slot_id => slot.id, :user_id => @user.id), class:"btn btn-sm btn-danger"%>
<div></div>
<br>

</div>