config/routes.rb
Rails.application.routes.draw do
  get 'slots/new'
  get 'rooms/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/openslot', to: 'slots#show'
  get '/adduser', to: 'srecords#new'
  get '/showSlotUsers', to: 'srecords#show'
  get '/addtoslot', to: 'srecords#new'
  post '/addtoslot', to: 'srecords#create'
  get '/response', to: 'urecords#yes'
  get '/responseno', to: 'urecords#no'
  get '/showroom', to: 'rooms#show'
   get  '/help',    to: 'static_pages#help'
   get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
get '/newroom', to: 'rooms#new'
post '/newroom', to: 'rooms#create'
  resources :users do
    resources :urecords
  end
    resources :rooms do
    resources :slots do
      resources :srecords
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Meeting Planner", current_user, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
                  <li><%= link_to "Dashboard", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>


        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<% @user= current_user %>
<div class="sidebar center" style="padding-top:3%">
  <h1>
    <%= gravatar_for @user %>
    <br>
    <br>
    <%= @user.name %>  </h1>

    <h4 class="center"><%= @user.email %>
</h4>
<br>
<br>
  <%= if @user.admin?
   link_to "Create New Room" , newroom_path , class: "btn btn-lg btn-info"
   end%>
   <h3>Total Meetings:

  <%= @user.urecord.count %>
  </h3>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meeting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= if logged_in?
        render 'layouts/sidebar'
        end%>
        <div class="display">
          <div class="bodcon">
      <% flash.each do |message_type, message| %>

     <div class="alert alert-<%= message_type %>"><%= message %></div>
   <% end %>
    <%= yield %>
    <?div>
    </div>
  </body>
</html>